package io.consumerweb.mfa.model;

public interface ConsumerWebMfaInfo {
	
	String ABORT_MFA = "ABORT_MFA";
	
	String LOCKOUT = "LOCKOUT";
	
	String ERROR_MFA = "ERROR_MFA";
	
	String RE_ENROLL = "RE_ENROLL";
	
	String ALLOW_LOGIN = "ALLOW_LOGIN";
	
	String CHALLENGE_LOGIN = "CHALLENGE_LOGIN";
	
	String CHALLENGE_SUCCESS ="CHALLENGE_SUCCESS";
	
	String AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
	
	String AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
	
	String INCIDENT_CREATED = "INCIDENT_CREATED";
	
	String REDIRECT_COLLECT = "REDIRECT_COLLECT";
	
	String VERIFIED = "VERIFIED";
	
	String UNLOCKED = "UNLOCKED";
	
	String NOTENROLLED = "NOTENROLLED";
	
	String ERROR_MFA_INCIDENT = "ERROR_MFA_INCIDENT";
	
	String DEVICE_TOKEN_COOKIE = "PMData";

}
